apiVersion: v1
kind: Service
metadata:
  name: echoweb
  labels:
    app: echo
spec:
  selector:
    app: echo
    tier: web
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: "YOUR.IP.ADDRESS.HERE"
